"""initial_metadata_schema

Revision ID: 72eef3739a47
Revises: 
Create Date: 2026-08-25 11:44:17.250128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72eef3739a47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_templates',
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('question_template', sa.Text(), nullable=False),
    sa.Column('retrieval_text', sa.Text(), nullable=False),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_query_templates_intent'), 'query_templates', ['intent'], unique=False)
    op.create_index(op.f('ix_query_templates_is_active'), 'query_templates', ['is_active'], unique=False)
    op.create_table('query_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('bound_parameters', sa.JSON(), nullable=False),
    sa.Column('result_row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['query_templates.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_execution_log_template_id'), 'query_execution_log', ['template_id'], unique=False)
    op.create_table('query_template_placeholders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('placeholder_name', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('input_mode', sa.String(length=50), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_id_column', sa.String(length=100), nullable=True),
    sa.Column('source_label_column', sa.String(length=100), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['query_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_template_placeholders_template_id'), 'query_template_placeholders', ['template_id'], unique=False)
    op.create_table('template_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nl_question', sa.Text(), nullable=False),
    sa.Column('expected_template_id', sa.String(length=50), nullable=False),
    sa.Column('expected_entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expected_template_id'], ['query_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_test_cases_expected_template_id'), 'template_test_cases', ['expected_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_test_cases_expected_template_id'), table_name='template_test_cases')
    op.drop_table('template_test_cases')
    op.drop_index(op.f('ix_query_template_placeholders_template_id'), table_name='query_template_placeholders')
    op.drop_table('query_template_placeholders')
    op.drop_index(op.f('ix_query_execution_log_template_id'), table_name='query_execution_log')
    op.drop_table('query_execution_log')
    op.drop_index(op.f('ix_query_templates_is_active'), table_name='query_templates')
    op.drop_index(op.f('ix_query_templates_intent'), table_name='query_templates')
    op.drop_table('query_templates')
    # ### end Alembic commands ###
